version: '3.8'

services:
  localstack:
    image: localstack/localstack:2.0.0
    ports:
      - "4566:4566"
      - "4510:4510"  # DynamoDB port
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack_volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build:
      context: .
      dockerfile: src/Dockerfile2.api
    ports:
      - "5000:5000"
    depends_on:
      - localstack

volumes:
  localstack_volume:
