version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4568:4566"
      - "4511:4510"  # DynamoDB port
    environment:
      - LOCALSTACK_PORT=4566
    volumes:
      - localstack_volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build:
      context: .
      dockerfile: src/Dockerfile2.api
    ports:
      - "5000:5000"
    depends_on:
      - localstack

volumes:
  localstack_volume:
