name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Verify Docker and Docker Compose versions
      run: |
        docker --version
        docker compose version

    - name: List files in the build context
      run: |
        ls -R

    - name: Build and run Docker Compose
      run: |
        docker compose -f docker-compose.yml up -d
        
    - name: Build Docker image for API
      run: docker build -f src/Dockerfile2.api -t my-api .

    - name: Build Docker image for tests
      run: docker build -f tests/Dockerfile2.test -t my-tests .

    - name: Run stack
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Run tests
      run: docker run --rm my-tests
