name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v2
      with:
        version: 2 # Specify the version of Docker Compose to use

    - name: Build and run Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Build Docker image for API
      run: docker build -f src/Dockerfile2.api -t my-api .


    - name: Build Docker image for tests
      run: docker build -f tests/Dockerfile2.test -t my-tests .

    - name: Run stack
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Run tests
      run: docker run --rm my-tests
